spring.application.name=paperless

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5433/paperless
spring.datasource.username=paperless
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable database access during web response rendering
spring.jpa.open-in-view=false